name: molai  # Replace 'molai' with your desired environment name
channels:
  - defaults
  - conda-forge  # Include other channels as necessary
dependencies:
  - python=3.9.18  # Specify Python version
  - absl-py=2.0.0
  - aiohttp=3.8.6
  - aioitertools=0.11.0
  - aiosignal=1.3.1
  - cffi=1.16.0
  - cryptography=41.0.4
  - numpy=1.24.4
  - pandas=2.1.1
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - xgboost  # Conda package; note that pip-installed packages will be under pip section
  - pip
  - pip:
    - alembic==1.13.1
    - altair==5.4.1
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==2.4.0
    - async-lru==2.0.4
    - async-timeout==4.0.3
    - attrs==23.1.0
    - babel==2.13.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - black==22.3.0
    - bleach==6.1.0
    - blinker==1.6.3
    - catboost==1.2.5
    - charset-normalizer==3.3.0
    - colorlog==6.8.2
    - comm==0.1.4
    - cython==0.29.37
    - debugpy==1.8.0
    - decorator==5.1.1
    - deepchem==2.8.0
    - defusedxml==0.7.1
    - dgl==2.2.1
    - dgllife==0.3.2
    - distlib==0.3.7
    - dnspython==2.4.2
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - e3nn==0.4.4
    - emmet-core==0.69.5
    - exceptiongroup==1.1.3
    - executing==2.0.0
    - fastapi==0.103.2
    - fastjsonschema==2.18.1
    - filelock==3.12.4
    - flask==3.0.0
    - frozenlist==1.4.0
    - fsspec==2023.9.2
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.37
    - google-api-core==2.19.1
    - google-api-python-client==2.142.0
    - google-auth==2.23.3
    - google-auth-httplib2==0.2.0
    - google-auth-oauthlib==1.0.0
    - googleapis-common-protos==1.63.2
    - greenlet==3.0.3
    - grpcio==1.58.1
    - hdbscan==0.8.37
    - hyperopt==0.2.7
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.0
    - ipykernel==6.25.2
    - ipython==8.12.3
    - itsdangerous==2.1.2
    - jedi==0.19.1
    - jinja2==3.1.2
    - joblib==1.3.2
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.4.0
    - jupyter-core==5.4.0
    - jupyter-events==0.7.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.7.3
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.7
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.0
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==3.0.2
    - mongogrant==0.3.3
    - mongomock==4.0.0
    - monty==2023.9.25
    - mp-api==0.37.2
    - mpmath==1.3.0
    - nbclient==0.8.0
    - nbconvert==7.16.4
    - nbformat==5.9.2
    - nest-asyncio==1.5.8
    - networkx==3.1
    - nodeenv==1.8.0
    - notebook-shim==0.2.3
    - oauthlib==3.2.2
    - ocp-models==0.0.3
    - orjson==3.9.8
    - overrides==7.4.0
    - packaging==23.2
    - pandas==2.1.1
    - paramiko==3.3.1
    - pathspec==0.11.2
    - pickleshare==0.7.5
    - pillow==10.0.1
    - pipreqs==0.5.0
    - plotly==5.17.0
    - pluggy==1.3.0
    - pre-commit==2.10.1
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.39
    - proto-plus==1.24.0
    - protobuf==4.24.3
    - psutil==5.9.5
    - pure-eval==0.2.2
    - py4j==0.10.9.7
    - pyarrow==17.0.0
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pybtex==0.24.0
    - pydeck==0.9.1
    - pyg==2.3.1
    - pygments==2.16.1
    - pyjwt==2.8.0
    - pymatgen==2023.5.10
    - pymongo==4.5.0
    - pynacl==1.5.0
    - pynndescent==0.5.13
    - pynng==0.7.2
    - pyopenssl==23.2.0
    - pyparsing==3.1.1
    - pytest==7.4.2
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - python-graphviz==0.20.3
    - python-json-logger==2.0.7
    - python-lmdb==1.4.1
    - python-tzdata==2023.3
    - pytz==2023.3.post1
    - pyu2f==0.1.5
    - pywin32==306
    - pyzmq==25.1.1
    - rdkit==2023.9.5
    - referencing==0.30.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rich==13.8.0
    - rsa==4.9
    - ruamel.yaml==0.17.35
    - scikit-learn==1.3.1
    - seaborn==0.13.2
    - selfies==2.1.1
    - send2trash==1.8.2
    - sentry-sdk==1.32.0
    - setproctitle==1.3.3
    - setuptools==68.2.2
    - sniffio==1.3.0
    - soupsieve==2.5
    - sqlalchemy==2.0.30
    - stack-data==0.6.3
    - starlette==0.27.0
    - streamlit==1.38.0
    - submitit==1.5.0
    - sympy==1.12
    - syrupy==3.0.6
    - tabulate==0.9.0
    - tenacity==8.2.3
    - tensorboard==2.14.1
    - terminado==0.17.1
    - threadpoolctl==3.2.0
    - tinycss2==1.2.1
    - torch==2.1.0
    - torch-scatter==2.1.2
    - torch-sparse==0.6.18
    - torchdata==0.7.1
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.11.2
    - typed-ast==1.5.5
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.12.2
    - umap-learn==0.5.6
    - uncertainties==3.1.7
    - unicodedata2==15.1.0
    - uritemplate==4.1.1
    - urllib3==2.0.6
    - wandb==0.15.12
    - watchdog==4.0.2
    - wcwidth==0.2.8
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - werkzeug==3.0.0
    - wheel==0.41.2
    - yarg==0.1.9
    - yarl==1.9.2
    - zipp==3.17.0

  # Add all other pip-installed packages following the same format
